apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: tools
spec:
  encryptedData:
    .dockerconfigjson: AgCyZmlVBlrtLOLhJtu8Bqo/WxA0tFX3WHq+DHeTzOHrsBhulGm+U8oKBjyuFTB7Wmca4bww+GirvydApeC8ZdWhgcWMHG7piD8HBjUxqCmxHKOwL+fdeO1lSL4uFkrm17tBhfCtbGVE4ZQD1PmZW+PaB0jLDmV56kbuKkvMV/HPaY5Mx8d7VLFIuwA5+DV+MOPQSqkxXB40Jt61LyqwiLEBQXwySZMAVow7z8WvcxPqXALMYk2guS9JX+ynJKU0pse0ypcCCSflHSxr8jmZLjAHg1Z7qSD+pB3XZAu1G6QSLsgsN/ln6WGnIxuVhqg0SLuGpEqCHUiruzFam8xJ5sA9NizpZFj0tAGH96j8tEQZeLCRBgwv3BOS/0C1ygvY82Fucd7fFBDLxYDcJrMJbW8o91GUM1AKz5HqQbUGfAKldbx0p6491MdbP6AXn+x3hcAwMl7q1NXgsNeckg22pKmFWyrx82lOOuwwjZREFGqSY2S6/VAW3imGgtPrYnN6xZ6MDs/eHC+W7hCHx5SAdhFcmM92l/uSh+d3CLKVxd56VSoA9jult3/RxaO3G8jhgKiY8eMwa4nVFqErXpkkaKMFZ3p+/FmwecqXVnEREG6x2kilcvmX6jFHG7W0GdVLETkXaZhfE4fKofW4Z61ixAunigqDTHkYsBMci8cyciTWqgs5NOErQbohfak87mRl4CB26k1/F+bw0vizXuNUGqQIlAd3ACqkXmJL6GxNM3Rq1bV8rRP7KVB/GaOo42ka9rvecpjVmLIAL7ZiDR3P98oht9mzqKV/VW691eQgV7jV8Au+iMk1eG8XEBJ4cdCyma6A+FVZ91Ug8whhP3wmPPzSYJJ5JYnBXnYIJ/QUclIw3ktq18Tm28MAXp2/bjudJ+jpv1Rmhog86c4pl4w4n95IRbEMrZpsnNE8wVItPaXZm0pT0Bi3WD/9nXxUsx3e5luoAUdtilOdyn+RsSIuq8CMJaxDvhwoqEhQIdqaDPaOnRKkoOpR911OUe8XAcUZXv13KXeySNsjlW0DQmmzSPTbNKBWq48u2VmPOZRmWs4LPONkLF89vYh6hDu2+qBH2FVSyb25IT9euzS2+VRJ4ezE1MughlXbzt2lUiHosKmFae52aSVUyLgNqvJAlSpzAhjyPYleNWeTE/Mf+djR2358wJLYWpwO3lQ4jPnJ1g9qqt1LWHZ1mFBv8vjmNfKiSBQcZ4QFJhEV6R4M9HJWO9RjccWr0hsxWiw8ocOAZKciKTBXQdjt9cP1UP0lMqXaP1eufv2iexxujyCftOL4EoJancx74bvRWWvoERy6GBE0v+K3OtjiTKD954O5cHidAoVG7/+kG7x52FIxdQVDNCZH6H+CizWu6GBcR0+Qvu8sJIufqmvx
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: tools
    type: kubernetes.io/dockerconfigjson

